apiVersion: v2
version: 3.0.3
name: openebs
appVersion: 3.0.1
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - iSCSI
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
maintainers:
  - name: kmova
    email: kiran.mova@mayadata.io
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
  - name: shovanmaity
    email: shovan.maity@mayadata.io
dependencies:
  - name: openebs-ndm
    version: "1.7.1"
    repository: "https://openebs.github.io/node-disk-manager"
    condition: openebs-ndm.enabled
  - name: localpv-provisioner
    version: "3.0.1"
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
    condition: localpv-provisioner.enabled
  - name: cstor
    version: "3.0.1"
    repository: "https://openebs.github.io/cstor-operators"
    condition: cstor.enabled
  - name: jiva
    version: "3.0.1"
    repository: "https://openebs.github.io/jiva-operator"
    condition: jiva.enabled
  - name: zfs-localpv
    version: "1.9.8"
    repository: "https://openebs.github.io/zfs-localpv"
    condition: zfs-localpv.enabled
  - name: lvm-localpv
    version: "0.8.5"
    repository: "https://openebs.github.io/lvm-localpv"
    condition: lvm-localpv.enabled
  - name: nfs-provisioner
    version: "0.7.1"
    repository: "https://openebs.github.io/dynamic-nfs-provisioner"
    condition: nfs-provisioner.enabled
