# Default values for openebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false
  # rbac.kyvernoEnabled: `true` if Kyverno Policy resources should be created
  kyvernoEnabled: false

serviceAccount:
  create: true
  name:

imagePullSecrets: []
# - name: image-pull-secret

release:
  # "openebs.io/version" label for control plane components
  version: "2.12.0"

image:
  pullPolicy: IfNotPresent
  repository: ""

# Legacy components will be installed if it is enabled.
# Legacy components are - admission-server, api-server, snapshot-operator
# and provisioner used by non-csi cstor and jiva provisioners
legacy:
  enabled: true

# Used by jiva and cstor (non csi) for volume management
# also installs and updates the CRDs for jiva and cstor (non-csi)
# Will be disabled in OpenEBS 3.0 in favor of CSI Drivers
apiserver:
  enabled: true
  image: "openebs/m-apiserver"
  imageTag: "2.12.0"
  replicas: 1
  ports:
    externalPort: 5656
    internalPort: 5656
  sparse:
    enabled: "false"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  # apiserver resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

# Used by apiserver to create default storage classes and pools.
defaultStorageConfig:
  enabled: "true"


# Directory used by the OpenEBS to store debug information and so forth
# that are generated in the course of running OpenEBS containers.
varDirectoryPath:
  baseDir: "/var/openebs"

# Out of tree Kubernetes provisioner for jiva and cstor
# Will be disabled in OpenEBS 3.0 in favor of CSI Drivers
provisioner:
  enabled: true
  image: "openebs/openebs-k8s-provisioner"
  imageTag: "2.12.0"
  replicas: 1
  enableLeaderElection: true
  patchJivaNodeAffinity: enabled
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  # provisioner resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

localprovisioner:
  enabled: true
  image: "openebs/provisioner-localpv"
  imageTag: "2.12.0"
  replicas: 1
  enableLeaderElection: true
  basePath: "/var/openebs/local"
  # This sets the number of times the provisioner should try
  # with a polling interval of 5 seconds, to get the Blockdevice
  # Name from a BlockDeviceClaim, before the BlockDeviceClaim
  # is deleted. E.g. 12 * 5 seconds = 60 seconds timeout
  waitForBDBindTimeoutRetryCount: "12"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  # localprovisioner resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

# Out of tree Kubernetes snapshot provisioner for cstor
# Will be disabled in OpenEBS 3.0 in favor of CSI Drivers
snapshotOperator:
  enabled: true
  controller:
    image: "openebs/snapshot-controller"
    imageTag: "2.12.0"
    # snapshot controller resource requests and limits
    # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi
  provisioner:
    image: "openebs/snapshot-provisioner"
    imageTag: "2.12.0"
    # snapshot provisioner resource requests and limits
    # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi
  replicas: 1
  enableLeaderElection: true
  upgradeStrategy: "Recreate"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60

ndm:
  enabled: true
  image: "openebs/node-disk-manager"
  imageTag: "1.6.1"
  sparse:
    path: "/var/openebs/sparse"
    size: "10737418240"
    count: "0"
  filters:
    enableOsDiskExcludeFilter: true
    osDiskExcludePaths: "/,/etc/hosts,/boot"
    enableVendorFilter: true
    excludeVendors: "CLOUDBYT,OpenEBS"
    enablePathFilter: true
    includePaths: ""
    excludePaths: "/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"
  probes:
    enableSeachest: false
  nodeSelector: {}
  tolerations: []
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  # ndm resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

ndmOperator:
  enabled: true
  image: "openebs/node-disk-operator"
  imageTag: "1.6.1"
  replicas: 1
  upgradeStrategy: Recreate
  nodeSelector: {}
  tolerations: []
  healthCheck:
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessCheck:
    initialDelaySeconds: 5
    periodSeconds: 10
  # ndmOperator resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 2Gi
  # requests:
  #   cpu: 500m
  #   memory: 1Gi

ndmExporter:
  enabled: false
  image:
    registry:
    repository: openebs/node-disk-exporter
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 1.6.1
  nodeExporter:
    name: ndm-node-exporter
    podLabels:
      name: openebs-ndm-node-exporter
    # The TCP port number used for exposing ndm-node-exporter metrics.
    # If not set, service will not be created to expose metrics endpoint to serviceMonitor
    # and listen-port flag will not be set and container port will be empty.
    metricsPort: 9101
    nodeSelector: {}
    tolerations: []
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    # ndm resource requests and limits
    # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi
  clusterExporter:
    name: ndm-cluster-exporter
    podLabels:
      name: openebs-ndm-cluster-exporter
    # The TCP port number used for exposing ndm-cluster-exporter metrics.
    # If not set, service will not be created to expose metrics endpoint to serviceMonitor
    # and listen-port flag will not be set and container port will be empty.
    metricsPort: 9100
    nodeSelector: {}
    tolerations: []
    healthCheck:
      initialDelaySeconds: 30
      periodSeconds: 60
    # ndm resource requests and limits
    # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

# Used by jiva and cstor (non csi) for validation the volume delete requests
# Will be disabled in OpenEBS 3.0 in favor of CSI Drivers
webhook:
  enabled: true
  image: "openebs/admission-server"
  imageTag: "2.12.0"
  failurePolicy: "Fail"
  replicas: 1
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  nodeSelector: {}
  tolerations: []
  affinity: {}
  hostNetwork: false
  # admission-server resource requests and limits
  # Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 1Gi
  # requests:
  #   cpu: 250m
  #   memory: 500Mi

# Used by ndm and localprovisioner to carry out tasks like
# creating or deleting directory, filesystem, etc.
helper:
  image: "openebs/linux-utils"
  imageTag: "2.12.0"

featureGates:
  enabled: true
  GPTBasedUUID:
    enabled: true
    featureGateFlag: "GPTBasedUUID"
  APIService:
    enabled: false
    featureGateFlag: "APIService"
    address: "0.0.0.0:9115"
  UseOSDisk:
    enabled: false
    featureGateFlag: "UseOSDisk"
  MountChangeDetection:
    enabled: false
    featureGateFlag: "MountChangeDetection"

crd:
  enableInstall: true

# Used by jiva and cstor (non csi) for validation the volume delete requests
# Will be disabled in OpenEBS 3.0 in favor of CSI Drivers
policies:
  monitoring:
    enabled: true
    image: "openebs/m-exporter"
    imageTag: "2.12.0"

analytics:
  enabled: true
  # Specify in hours the duration after which a ping event needs to be sent.
  pingInterval: "24h"

jiva:
  # non csi configuration
  image: "openebs/jiva"
  imageTag: "2.12.1"
  replicas: 3
  defaultStoragePath: "/var/openebs"

  # jiva csi driver configuration
  # do not enable or configure any sub dependency here
  # only jiva csi related settings can be added here
  # ref - https://openebs.github.io/jiva-operator

  enabled: false

  # Sample configuration if you want to configure jiva csi driver with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/jiva-operator

#  rbac:
#    create: true
#    pspEnabled: false
#
#  jivaOperator:
#    controller:
#      image:
#        registry:
#        repository: openebs/jiva
#        tag: 2.12.1
#    replica:
#      image:
#        registry:
#        repository: openebs/jiva
#        tag: 2.12.1
#    image:
#      registry:
#      repository: openebs/jiva-operator
#      pullPolicy: IfNotPresent
#      tag: 2.12.1
#
#  jivaCSIPlugin:
#    remount: "true"
#    image:
#      registry:
#      repository: openebs/jiva-csi
#      pullPolicy: IfNotPresent
#      tag: 2.12.1

cstor:

  # non csi configuration
  pool:
    image: "openebs/cstor-pool"
    imageTag: "2.12.0"
  poolMgmt:
    image: "openebs/cstor-pool-mgmt"
    imageTag: "2.12.0"
  target:
    image: "openebs/cstor-istgt"
    imageTag: "2.12.0"
  volumeMgmt:
    image: "openebs/cstor-volume-mgmt"
    imageTag: "2.12.0"

  # cstor csi driver configuration
  # do not enable or configure any sub dependency here
  # only cstor csi related settings can be added here
  # ref - https://openebs.github.io/cstor-operators

  enabled: false

  # Sample configuration if you want to configure cstor csi driver with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/cstor-operators

#  imagePullSecrets: []
#
#  rbac:
#    create: true
#    pspEnabled: false
#
#  cspcOperator:
#    poolManager:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-pool-manager
#        tag: 2.12.0
#    cstorPool:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-pool
#        tag: 2.12.0
#    cstorPoolExporter:
#      image:
#        registry: quay.io/
#        repository: openebs/m-exporter
#        tag: 2.12.0
#    image:
#      registry: quay.io/
#      repository: openebs/cspc-operator
#      pullPolicy: IfNotPresent
#      tag: 2.12.0
#
#  cvcOperator:
#    target:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-istgt
#        tag: 2.12.0
#    volumeMgmt:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-volume-manager
#        tag: 2.12.0
#    volumeExporter:
#      image:
#        registry: quay.io/
#        repository: openebs/m-exporter
#        tag: 2.12.0
#    image:
#      registry: quay.io/
#      repository: openebs/cvc-operator
#      pullPolicy: IfNotPresent
#      tag: 2.12.0
#
#  cstorCSIPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/cstor-csi-driver
#      pullPolicy: IfNotPresent
#      tag: 2.12.0
#
#  admissionServer:
#    componentName: cstor-admission-webhook
#    image:
#      registry: quay.io/
#      repository: openebs/cstor-webhook
#      pullPolicy: IfNotPresent
#      tag: 2.12.0


# zfs local pv configuration goes here
# ref - https://openebs.github.io/zfs-localpv
zfs-localpv:
  enabled: false

  # Sample configuration if you want to configure zfs locapv with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/zfs-localpv

#  imagePullSecrets: []
#
#  rbac:
#    pspEnabled: false
#
#  zfsPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/zfs-driver
#      pullPolicy: IfNotPresent
#      tag: 1.9.1

# lvm local pv configuration goes here
# ref - https://openebs.github.io/lvm-localpv
lvm-localpv:
  enabled: false

  # Sample configuration if you want to configure lvm localpv with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/lvm-localpv

#  imagePullSecrets: []
#
#  rbac:
#    pspEnabled: false
#
#  lvmPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/lvm-driver
#      pullPolicy: IfNotPresent
#      tag: 0.8.0

# openebs nfs provisioner configuration goes here
# ref - https://openebs.github.io/dynamic-nfs-provisioner
nfs-provisioner:
  enabled: false

  # Sample configuration if you want to configure lvm localpv with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/dynamic-nfs-provisioner

#  imagePullSecrets: []
#
#  rbac:
#    pspEnabled: false
#
#  nfsProvisioner:
#    image:
#      registry:
#      repository: openebs/provisioner-nfs
#      tag: 0.6.0
#      pullPolicy: IfNotPresent
#    enableLeaderElection: "true"

cleanup:
  image:
    # Make sure that registry name end with a '/'.
    # For example : quay.io/ is a correct value here and quay.io is incorrect
    registry:
    repository: bitnami/kubectl
    tag:
