# Default values for openebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  name:

imagePullSecrets: []
  #  - name: image-pull-secret

release:
  # "openebs.io/version" label for control plane components
  version: "2.10.0"

cleanup:
  image:
    # Make sure that registry name end with a '/'.
    # For example : quay.io/ is a correct value here and quay.io is incorrect
    registry:
    repository: bitnami/kubectl
    tag:
  tolerations: []

# jiva csi driver configuration
# do not enable or configure any sub dependency here
# only jiva csi related settings can be added here
# ref - https://openebs.github.io/jiva-operator

# jiva chart dependency tree is here -
# jiva
# | - localpv-provisioner
# | | - openebs-ndm

# Enable localpv-provisioner and openebs-ndm as root dependency not as
# sub dependency.
# openebs
# | - jiva(enable)
# | | - localpv-provisioner(disable)
# | | | - openebs-ndm(disable)
# | - localpv-provisioner(enable)
# | - openebs-ndm(enable)
jiva:
  enabled: false
  openebsLocalpv:
    enabled: false
  localpv-provisioner:
    openebsNDM:
      enabled: false

# Sample configuration if you want to configure jiva csi driver with custom values.
# This is a small part of the full configuration. Full configuration available
# here - https://openebs.github.io/jiva-operator

#  rbac:
#    create: true
#    pspEnabled: false
#
#  jivaOperator:
#    controller:
#      image:
#        registry: quay.io/
#        repository: openebs/jiva
#        tag: 2.10.0
#    replica:
#      image:
#        registry: quay.io/
#        repository: openebs/jiva
#        tag: 2.10.0
#    image:
#      registry: quay.io/
#      repository: openebs/jiva-operator
#      pullPolicy: IfNotPresent
#      tag: 2.10.1
#
#  jivaCSIPlugin:
#    remount: "true"
#    image:
#      registry: quay.io/
#      repository: openebs/jiva-csi
#      pullPolicy: IfNotPresent
#      tag: 2.10.1

# cstor csi driver configuration
# do not enable or configure any sub dependency here
# only cstor csi related settings can be added here
# ref - https://openebs.github.io/cstor-operators

# cstor chart dependency tree is here -
# cstor
# | - openebs-ndm

# Enable openebs-ndm as root dependency not as sub dependency.
# openebs
# | - cstor(enable)
# | | - openebs-ndm(disable)
# | - openebs-ndm(enable)
cstor:
  enabled: false
  openebsNDM:
    enabled: false

# Sample configuration if you want to configure cstor csi driver with custom values.
# This is a small part of the full configuration. Full configuration available
# here - https://openebs.github.io/cstor-operators

#  imagePullSecrets: []
#
#  rbac:
#    create: true
#    pspEnabled: false
#
#  cspcOperator:
#    poolManager:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-pool-manager
#        tag: 2.10.0
#    cstorPool:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-pool
#        tag: 2.10.0
#    cstorPoolExporter:
#      image:
#        registry: quay.io/
#        repository: openebs/m-exporter
#        tag: 2.10.0
#    image:
#      registry: quay.io/
#      repository: openebs/cspc-operator
#      pullPolicy: IfNotPresent
#      tag: 2.10.0
#
#  cvcOperator:
#    target:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-istgt
#        tag: 2.10.0
#    volumeMgmt:
#      image:
#        registry: quay.io/
#        repository: openebs/cstor-volume-manager
#        tag: 2.10.0
#    volumeExporter:
#      image:
#        registry: quay.io/
#        repository: openebs/m-exporter
#        tag: 2.10.0
#    image:
#      registry: quay.io/
#      repository: openebs/cvc-operator
#      pullPolicy: IfNotPresent
#      tag: 2.10.0
#
#  cstorCSIPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/cstor-csi-driver
#      pullPolicy: IfNotPresent
#      tag: 2.10.0
#
#  admissionServer:
#    componentName: cstor-admission-webhook
#    image:
#      registry: quay.io/
#      repository: openebs/cstor-webhook
#      pullPolicy: IfNotPresent
#      tag: 2.10.0

# ndm configuration goes here
# https://openebs.github.io/node-disk-manager
openebs-ndm:
  enabled: false

# Sample configuration if you want to configure openebs ndm with custom values.
# This is a small part of the full configuration. Full configuration available
# here - https://openebs.github.io/node-disk-manager

#  imagePullSecrets: []
#
#  ndm:
#    image:
#      registry: quay.io/
#      repository: openebs/node-disk-manager
#      pullPolicy: IfNotPresent
#      tag: 1.5.0
#    sparse:
#      path: "/var/openebs/sparse"
#      size: "10737418240"
#      count: "0"
#    filters:
#      enableOsDiskExcludeFilter: true
#      osDiskExcludePaths: "/,/etc/hosts,/boot"
#      enableVendorFilter: true
#      excludeVendors: "CLOUDBYT,OpenEBS"
#      enablePathFilter: true
#      includePaths: ""
#      excludePaths: "loop,fd0,sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"
#    probes:
#      enableSeachest: false
#      enableUdevProbe: true
#      enableSmartProbe: true
#
#  ndmOperator:
#    image:
#      registry: quay.io/
#      repository: openebs/node-disk-operator
#      pullPolicy: IfNotPresent
#      tag: 1.5.0
#
#  helperPod:
#    image:
#      registry: quay.io/
#      repository: openebs/linux-utils
#      pullPolicy: IfNotPresent
#      tag: 2.10.0
#
#  featureGates:
#    enabled: true
#    GPTBasedUUID:
#      enabled: true
#      featureGateFlag: "GPTBasedUUID"
#    APIService:
#      enabled: true
#      featureGateFlag: "APIService"
#      address: "0.0.0.0:9115"
#    UseOSDisk:
#      enabled: false
#      featureGateFlag: "UseOSDisk"
#
#  varDirectoryPath:
#    baseDir: "/var/openebs"

# local pv provisioner configuration goes here
# do not enable or configure any sub dependency here
# ref - https://openebs.github.io/dynamic-localpv-provisioner

# local pv chart dependency tree is here -
# localpv-provisioner
# | - openebs-ndm

# Enable openebs-ndm as root dependency not as sub dependency.
# openebs
# | - localpv-provisioner(enable)
# | | - openebs-ndm(disable)
# | - openebs-ndm(enable)
localpv-provisioner:
  enabled: false
  openebsNDM:
    enabled: false

# Sample configuration if you want to configure openebs locapv with custom values.
# This is a small part of the full configuration. Full configuration available
# here - https://openebs.github.io/dynamic-localpv-provisioner

#  imagePullSecrets: []
#
#  rbac:
#    create: true
#    pspEnabled: false
#
#  localpv:
#    image:
#      registry: quay.io/
#      repository: openebs/provisioner-localpv
#      tag: 2.10.0
#      pullPolicy: IfNotPresent
#    healthCheck:
#      initialDelaySeconds: 30
#      periodSeconds: 60
#    replicas: 1
#    enableLeaderElection: true
#    basePath: "/var/openebs/local"
#
#  helperPod:
#    image:
#      registry: quay.io/
#      repository: openebs/linux-utils
#      pullPolicy: IfNotPresent
#      tag: 2.10.0

# zfs local pv configuration goes here
# ref - https://openebs.github.io/zfs-localpv
zfs-localpv:
  enabled: false

# Sample configuration if you want to configure zfs locapv with custom values.
# This is a small part of the full configuration. Full configuration available
# here - https://openebs.github.io/zfs-localpv

#  imagePullSecrets: []
#
#  rbac:
#    pspEnabled: false
#
#  zfsPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/zfs-driver
#      pullPolicy: IfNotPresent
#      tag: 1.7.0

# lvm local pv configuration goes here
# ref - https://openebs.github.io/lvm-localpv
lvm-localpv:
  enabled: false

  # Sample configuration if you want to configure lvm locapv with custom values.
  # This is a small part of the full configuration. Full configuration available
  # here - https://openebs.github.io/lvm-localpv

#  imagePullSecrets: []
#
#  rbac:
#    pspEnabled: false
#
#  lvmPlugin:
#    image:
#      registry: quay.io/
#      repository: openebs/lvm-driver
#      pullPolicy: IfNotPresent
#      tag: 0.5.0
