{{- if .Values.localprovisioner.enabled }}
{{- $localpvprovisionerValues := index .Values "localpv-provisioner" }}
{{- if not $localpvprovisionerValues.enabled }}
# The second operand in the OR operation can be remove
# when enableHostpathClass is deprecated.
{{- if and (eq .Values.localprovisioner.hostpathClass.enabled true) (eq .Values.localprovisioner.enableHostpathClass true) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
{{- if or .Values.localprovisioner.basePath .Values.localprovisioner.hostpathClass.basePath }}
      - name: BasePath
        value: {{ .Values.localprovisioner.hostpathClass.basePath | default .Values.localprovisioner.basePath | quote }}
{{- end }}
{{- if .Values.localprovisioner.hostpathClass.nodeAffinityLabels }}
      - name: NodeAffinityLabels
        list:
{{ toYaml .Values.localprovisioner.hostpathClass.nodeAffinityLabels | indent 10 }}
{{- end }}
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end }}
{{- end }}
{{- end }}
